import reflex as rx
from ..states import State


def selector_idioma_portada() -> rx.Component:
    """Selector de idioma para la portada con redirección"""
    return rx.hstack(
        rx.button(
            "ES",
            on_click=[State.cambiar_idioma("es"), rx.redirect("/home")],
            bg=rx.cond(State.idioma == "es", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "es", "#000000", "#CCCCCC"),
            width="60px",
            height="45px",
            font_size="16px",
            font_weight="600",
            border=rx.cond(State.idioma == "es", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="8px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "es", "#FFFFFF", "#2a2a2a"), "transform": "scale(1.05)"},
            transition="all 0.2s ease",
        ),
        rx.button(
            "EN",
            on_click=[State.cambiar_idioma("en"), rx.redirect("/home")],
            bg=rx.cond(State.idioma == "en", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "en", "#000000", "#CCCCCC"),
            width="60px",
            height="45px",
            font_size="16px",
            font_weight="600",
            border=rx.cond(State.idioma == "en", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="8px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "en", "#FFFFFF", "#2a2a2a"), "transform": "scale(1.05)"},
            transition="all 0.2s ease",
        ),
        rx.button(
            "IT",
            on_click=[State.cambiar_idioma("it"), rx.redirect("/home")],
            bg=rx.cond(State.idioma == "it", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "it", "#000000", "#CCCCCC"),
            width="60px",
            height="45px",
            font_size="16px",
            font_weight="600",
            border=rx.cond(State.idioma == "it", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="8px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "it", "#FFFFFF", "#2a2a2a"), "transform": "scale(1.05)"},
            transition="all 0.2s ease",
        ),
        rx.button(
            "CA",
            on_click=[State.cambiar_idioma("ca"), rx.redirect("/home")],
            bg=rx.cond(State.idioma == "ca", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "ca", "#000000", "#CCCCCC"),
            width="60px",
            height="45px",
            font_size="16px",
            font_weight="600",
            border=rx.cond(State.idioma == "ca", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="8px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "ca", "#FFFFFF", "#2a2a2a"), "transform": "scale(1.05)"},
            transition="all 0.2s ease",
        ),
        spacing="4",
    )


def selector_idioma() -> rx.Component:
    """Selector de idioma para navbar (sin redirección)"""
    return rx.hstack(
        rx.button(
            "ES",
            on_click=State.cambiar_idioma("es"),
            bg=rx.cond(State.idioma == "es", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "es", "#000000", "#CCCCCC"),
            width="50px",
            height="35px",
            font_size="14px",
            font_weight="600",
            border=rx.cond(State.idioma == "es", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="6px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "es", "#FFFFFF", "#2a2a2a")},
            transition="all 0.2s ease",
        ),
        rx.button(
            "EN",
            on_click=State.cambiar_idioma("en"),
            bg=rx.cond(State.idioma == "en", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "en", "#000000", "#CCCCCC"),
            width="50px",
            height="35px",
            font_size="14px",
            font_weight="600",
            border=rx.cond(State.idioma == "en", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="6px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "en", "#FFFFFF", "#2a2a2a")},
            transition="all 0.2s ease",
        ),
        rx.button(
            "IT",
            on_click=State.cambiar_idioma("it"),
            bg=rx.cond(State.idioma == "it", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "it", "#000000", "#CCCCCC"),
            width="50px",
            height="35px",
            font_size="14px",
            font_weight="600",
            border=rx.cond(State.idioma == "it", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="6px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "it", "#FFFFFF", "#2a2a2a")},
            transition="all 0.2s ease",
        ),
        rx.button(
            "CA",
            on_click=State.cambiar_idioma("ca"),
            bg=rx.cond(State.idioma == "ca", "#EEEEEE", "#1a1a1a"),
            color=rx.cond(State.idioma == "ca", "#000000", "#CCCCCC"),
            width="50px",
            height="35px",
            font_size="14px",
            font_weight="600",
            border=rx.cond(State.idioma == "ca", "2px solid #EEEEEE", "2px solid #333"),
            border_radius="6px",
            cursor="pointer",
            _hover={"bg": rx.cond(State.idioma == "ca", "#FFFFFF", "#2a2a2a")},
            transition="all 0.2s ease",
        ),
        spacing="3",
    )
